# Generated by Django 5.0.6 on 2024-05-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_imag'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='catimg')),
            ],
        ),
        migrations.AlterField(
            model_name='imag',
            name='image',
            field=models.ImageField(upload_to='catimg'),
        ),
    ]
