# Generated by Django 5.0.6 on 2024-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_category_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='mob',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
